name: test secert and ssh actions
on: [push]

jobs:
  SECRET-SSH-ACTIONS:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script: |
            pwd
            ls -l
            touch secret.txt
            echo ${{ secrets.MY_SECRET }} >> secret.txt
